### ISSUE TITLE
Add version timestamp to third party module's page

### ISSUE THREAD

**Issue by cknight** [denoland/deno_website2#1509] opened 2020-09-15 21:35 UTC
3rd party modules are viewed on a version basis.  It would be great to see the timestamp on the page of when that version was created to give the viewer an idea of currency of the version being viewed.

**Comment by tokiedokie** [comment] 2020-09-15 22:29
Duplicate of #1506

**Comment by lucacasonato** [comment] 2020-09-15 22:30
I don't think it is a duplicate - #1506 is for stats at the bottom of deno.land/x, and this issue is for individual version pages

**Comment by tokiedokie** [comment] 2020-09-15 22:35
@lucacasonato I misread it. you are right

**Comment by mumumilk** [comment] 2020-10-01 14:01
Where do y'all think is the best place to display this timestamp?

**Comment by cknight** [comment] 2020-10-01 20:30
This was my thinking, placing the tagged date just under the select box of the version:

![image](https://user-images.githubusercontent.com/1248238/94859918-38ec9400-042d-11eb-9dce-3ffe6fa4aea2.png)

**Comment by littletof** [comment] 2020-10-01 21:24
Just an idea, but maybe it could be added after the selected version like:
![image](https://user-images.githubusercontent.com/32012862/94864782-cdaabe00-043c-11eb-87ac-50027a03a428.png)

Although with the current setup you couldn't style it differently than the tag name, like giving it a lighter color 😕

**Closed** 2020-10-24 13:43 UTC
