### ISSUE TITLE
Compliance with new "main branch" upcoming github changes

### ISSUE THREAD

**Issue by xpyxel** [denoland/deno_website2#1224] opened 2020-06-25 00:28 UTC
there's plans to rename "master" to "main" in a lot of repos in favor of the BLM movement, among other reasons, see [this article](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) on zdnet. Currently my repository [Dash](https://github.com/xpyxel/dash) has renamed it's main branch to `main` and due to this, attempting to load master fails on https://deno.land/x/dash. 

An easy fix for this would to be to check if `master` exists, and if it doesn't get the default branch name of the repository and then instead fetch that branch.

**Comment by nayeemrmn** [comment] 2020-06-25 00:44
Duplicate of #1130.

**Closed** 2020-06-25 00:45 UTC
