### ISSUE TITLE
Dark mode Toggle 

### ISSUE THREAD

**Issue by jasbirrajrana** [denoland/deno_website2#1758] opened 2021-05-18 10:14 UTC
Working in front of a bright monitor under low light conditions, especially at night, can be stressful for the eyes. There's a reason why so many developers prefer dark themes for their text editors and terminals. The same reasons might be also applicable to the Deno Website. The interaction under such conditions could be improved by adding an optional dark mode (similar to Github).

ping me if I can work on it 👍🏻 Thanks!

**Comment by wperron** [comment] 2021-05-18 12:35
There's already two PRs opened for this (#1548  and #1672 ) both of which seem abandoned, so feel free to work on it :+1:

**Comment by jasbirrajrana** [comment] 2021-05-18 16:10
@wperron yep working 👍🏻

**Comment by kitsonk** [comment] 2021-06-22 23:32
Duplicate of #409

**Closed by kitsonk** 2021-06-22 23:32 UTC
Labels: duplicate
