### ISSUE TITLE
@versions to list down all versions of a module [Enhancement]

### ISSUE THREAD

**Issue by therealadityashankar** [denoland/deno_website2#461] opened 2020-05-14 13:08 UTC
any version management service requires being able to discover all the available versions,

lets say in a module, I use

```js
import something from "https://deno.land/x/something@1.2.0/main.ts"
```

it'd be nice if I could do something similar to

```sh
curl https://deno.land/x/something@versions
```
if it'd return

```json
{"versions": ["0.0.1", "1.0.0", "1.0.1", "1.1.0", "1.2.0", "2.0", "2.1"]}
```

there's currently no standardised way of discovering all available versions of a file,

currently, for example, [deno-udd](https://github.com/hayd/deno-udd), uses a variety of techniques to find all available versions, including
- checking github releases
- web scraping

apart from the other issues in this (like github's rate limiting), there is no standard, meaning that every person who hosts a file on their site will have to tell deno-udd to be able to support their website, and every other deno version management service like deno-udd to be able to support their website, and like, what may be a standard way in one version management service might not be supported in another

I like the `@versions` method cause is simple, and probably super easy to implement

further, it'd be even better if it could support additional parameters like
```json
{
    "versions": ["0.0.1", "1.0.0", "1.0.1", "1.1.0", "2.0", "2.6.9"],
    "deprecated": ["1.*"],
    "fatal-risk-of-use": ["<1.0.0"],
    "dog-person-wrote-code": false,
    "cat-person-wrote-code": true
}
```

relevant issue https://github.com/hayd/deno-udd/issues/10

**Comment by sidvishnoi** [comment] 2020-05-14 21:24
> another option - might be GraphQl github requests, which I believe work with lesser rate limiting restrictions

GraphQL API requires a GitHub token.

**Comment by therealadityashankar** [comment] 2020-05-14 22:17
is there a reason we're not using one ?, it seems quite easy to get one tbh

**Comment by sidvishnoi** [comment] 2020-05-14 22:27
> is there a reason we're not using one ?, it seems quite easy to get one tbh

The website is mostly client-side. That would mean exposing a GitHub token on the frontend (as we won't be asking user to login or enter a GitHub token to view stats, someone would need to make their GitHub token public - which is bad).

**Comment by therealadityashankar** [comment] 2020-05-14 22:51
I guess the major issue i'm trying to say is that every user will have to manually check the github releases page for every package to stay up-to date, this is problematic in the long run, especially by packages that have a long list of dependencies

I think the worker approach is for the best here

**Comment by lucacasonato** [comment] 2020-05-15 13:27
@therealadityashankar /x/ already has a drop down for version information that is requested client side. No need to go to Github.

**Comment by therealadityashankar** [comment] 2020-05-15 14:01
I hope this conversation does not start to get frustrating, I can understand if it does, :heart: 

basically, so if anyone needs to find version information (branch information in this case), they'd have to goto the deno website and check manually, which obviously, as I mentioned above is problematic if someone has a log list of dependencies

moreover, if one wants to automate this procedure (i.e. put it in a version checking software to help dependencies stay up-to-date), they'd have to scrape the deno website to do it, 

- which can put unnecessary load on the deno website,
- and isn't standardized, and hence removes decentralization, i.e., if one is creating a serious project,
 they'd be forced to be dependent on the deno.land interface (or a short list of urls) so that tools like deno-udd can stay up-to-date with version information, basically, it'd become impossible to host information on custom urls, which actually benefits the deno community, since if people host files on their custom domains, it reduces the strain on the main deno site

I personally like the @version interface, because anybody can easy implement it on their own website, and its easy to check by deno-udd if the url supports the interface, i.e., it'll 404 if it does not support it, send a json if it supports it

**Comment by buckle2000** [comment] 2020-05-16 11:36
The website (like https://deno.land/std/encoding/utf8.ts) also has no version at all. I have to go to https://deno.land/std/ and click on `version.ts` to check the latest version. It's inconvenient.

**Comment by lucacasonato** [comment] 2020-05-16 12:44
> The website (like https://deno.land/std/encoding/utf8.ts) also has no version at all. I have to go to https://deno.land/std/ and click on version.ts to check the latest version. It's inconvenient.

@buckle2000 There is a version dropdown:
![image](https://user-images.githubusercontent.com/7829205/82120009-56bda300-9783-11ea-8d42-fa59dceb3fe8.png)

---

While this proposal would be cool, but its not possible due to limitations with the GitHub API. /x has over 200 modules - which each have a paginated response in the GitHub API, thus needing multiple requests to get the full version list. That means we would have to do a lot of requests every hour to keep the version list up to date. While it may be currently possible using the rate limit that you get with a personal access token, `/x` will grow and we will need to do more requests every hour to keep the list up to date. At seem point we will hit even the PAT rate limit. What do we do then? Shut down the service? We can not implement this in a easily scalable way.

**Comment by buckle2000** [comment] 2020-05-16 13:52
I totally missed it! Thanks!

**Comment by therealadityashankar** [comment] 2020-05-16 13:58
this is an understandable answer, I'm closing the issue for now, thanks for the help @lucacasonato, @buckle2000, @sidvishnoi, @kitsonk  :heart:

**Comment by therealadityashankar** [comment] 2020-05-16 15:25
Reopening the issue because I just realised that in GraphQL, this **does not exceed the rate limit** !, and is **not an expensive operation**

the cost of this operation in graphql is 1/5000,

don't believe me, test it your self using this - https://gist.github.com/therealadityashankar/ffa2fa9a8001cc48b6c5dfe37fc61200

if you're using a linux computer, you could do -
- `wget https://gist.githubusercontent.com/therealadityashankar/ffa2fa9a8001cc48b6c5dfe37fc61200/raw/85c2e7120f0955887a93852af817600c9b4834b3/getAllVersions.mjs`

- then replace the variable PAT in line 1 to your own using a text editor,

the code in the end gives me the output
```
cost of operation : 1 limit : 5000
{ limit: 5000, cost: 1, remaining: 4980, resetAt: "2020-05-16T15:40:03Z" }
```

**Comment by therealadityashankar** [comment] 2020-05-16 15:31
![betty white dabbing](https://media.giphy.com/media/A4R8sdUG7G9TG/giphy.gif)
<p><a href="https://giphy.com/gifs/A4R8sdUG7G9TG">via GIPHY</a></p>

I hope this does not become a curb your enthusiasm thing, it might, LMAO

**Comment by buckle2000** [comment] 2020-05-16 16:07
That's only for Github repos though.

**Comment by therealadityashankar** [comment] 2020-05-16 16:11
@buckle2000, and deno.land also only works for github repos

**Comment by lucacasonato** [comment] 2020-05-16 16:55
> deno.land also only works for github repos

@therealadityashankar That is not correct. It can also proxy any URL or packages from NPM.

There might be a solution for the rate limit. I will look into this further.

**Comment by kidonng** [comment] 2020-05-16 16:55
Why bother about GitHub's rate limit when we have CDN like jsDelivr?

https://data.jsdelivr.com/v1/package/gh/denoland/deno

This is pretty simple to implement.

**Comment by therealadityashankar** [comment] 2020-05-16 18:49
the above link does not work

**Comment by therealadityashankar** [comment] 2020-05-17 07:07
hey !, I'm willing to contribute, so if you're comfortable with it can I open a pull request with support for this ?

**Comment by therealadityashankar** [comment] 2020-05-21 17:14
I wouldn't recommend jsdelivr, I've been attempting to use its API in another project, as far as I can say, the github links have issues, and often don't work

**Comment by lucacasonato** [comment] 2020-08-03 20:39
Duplicate of #138 which has been fixed.

**Closed by lucacasonato** 2020-08-03 20:39 UTC
