### ISSUE TITLE
Docs seem broken

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno_website2#1726] opened 2021-03-31 22:38 UTC
![image](https://user-images.githubusercontent.com/60560109/113219910-4e157480-9250-11eb-8a7c-cd90d0084835.png)

I challenge you to find the error. 

Edit: Seems like parameters are off (, ...)

**Comment by kt3k** [comment] 2021-04-01 03:10
Is that this page?
https://doc.deno.land/builtin/stable

The page looks normal to me.. It's strange... 🤔 
<img width="1061" alt="スクリーンショット 2021-04-01 12 08 52" src="https://user-images.githubusercontent.com/613956/113238140-17d50500-92e3-11eb-89a9-c75b88fbd83e.png">

**Comment by andreespirela** [comment] 2021-04-01 03:53
I think this was fixed by @ry

**Comment by kt3k** [comment] 2021-04-01 06:37
Right. Seems fixed by this commit https://github.com/denoland/doc_website/pull/177

Closing

**Closed by kt3k** 2021-04-01 06:37 UTC
Labels: needs info

**Comment by kidonng** [comment] 2021-04-07 07:16
Seems to be caused by [this change](https://github.com/denoland/doc_website/pull/176/files#diff-e9af3e12120ee5930bbbca8d5cf8c35382934ca3bd4c06dd33848e647a596d24). However, without the change the doc won't render. Sorry for causing the trouble, I will try to find a correct fix.
